@startuml

hide empty member
hide circle

package junit {
interface Extension
interface 拡張ポイントインタフェース
class 動かす仕組み
}

Extension <|-- 拡張ポイントインタフェース
拡張ポイントインタフェース <-l- 動かす仕組み

package 自分で作るもの {
class 独自拡張
class テスト
}

拡張ポイントインタフェース <|.. 独自拡張
独自拡張 -r-> テスト

@enduml
